language: java

sudo: false
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.sonar/installs'

addons:
  sonarqube: true

notifications:
  email: false

addons:
  sonarcloud:
    organization: "AT-NicolasMetivier"
    token:
      secure: projettest  # encrypted value of your token
# Script to execute.

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=at-nicolasmetivier-github -Dsonar.login=d217f2a7b06684f932ec72bbc294e27e87d9c361
